notifications:
  recipients:
    - kou@clear-code.com
rvm:
  - 1.8.7
  - 1.9.3
install:
  - echo "deb http://downloads.sourceforge.net/project/cutter/ubuntu/ $(lsb_release --short --codename) main" | sudo tee /etc/apt/sources.list.d/cutter.list
  - sudo apt-get install -y autotools-dev intltool libglib2.0-dev ruby1.8-dev ruby1.9.1-dev
before_script:
  - ./autogen.sh
  - ./configure
script:
  - test/run-test.sh
