version: "2"
services:
  ubuntu-trusty:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ubuntu-trusty
    command: tail -f /dev/null

  ubuntu-xenial:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ubuntu-xenial
    command: tail -f /dev/null

  ubuntu-zesty:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ubuntu-zesty
    command: tail -f /dev/null

  debian-jessie:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-debian-jessie
    command: tail -f /dev/null

  debian-stretch:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-debian-stretch
    command: tail -f /dev/null

  debian-sid:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-debian-sid
    command: tail -f /dev/null

  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-centos7
    command: tail -f /dev/null
